stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - yarn build

test:
  stage: test
  script:
    - yarn test:unit:ci

deploy:
  stage: deploy
  script:
    - firebase deploy --only hosting